### ISSUE TITLE
Can't run the code

### ISSUE THREAD

**Issue by borgr** [yz-joey/ACLPUB#3]
Hi,
Possibly related to (https://stackoverflow.com/questions/52699608/wand-policy-error-error-constitute-c-readimage-412)
I cloned pip installed etc. I also chmod'ed to 777 the pdf, but I get the following:
python3 aclpub_check/formatchecker.py --paper_type long ~/Downloads/NAACL_HLT_2021_BERT_project.pdf 
Checking /home/leshem/Downloads/NAACL_HLT_2021_BERT_project.pdf
Traceback (most recent call last):
  File "/home/leshem/ACLPUB/aclpub_check/formatchecker.py", line 352, in <module>
    main()
  File "/home/leshem/ACLPUB/aclpub_check/formatchecker.py", line 349, in main
    worker(submission)
  File "/home/leshem/ACLPUB/aclpub_check/formatchecker.py", line 314, in worker
    Formatter().format_check(submission=pdf_path, paper_type=args.paper_type)
  File "/home/leshem/ACLPUB/aclpub_check/formatchecker.py", line 65, in format_check
    self.check_page_margin()
  File "/home/leshem/ACLPUB/aclpub_check/formatchecker.py", line 173, in check_page_margin
    im = self.pdf.pages[page].to_image(resolution=150)
  File "/home/leshem/ACLPUB/env/lib/python3.9/site-packages/pdfplumber/page.py", line 299, in to_image
    return PageImage(self, **kwargs)
  File "/home/leshem/ACLPUB/env/lib/python3.9/site-packages/pdfplumber/display.py", line 53, in __init__
    self.original = get_page_image(
  File "/home/leshem/ACLPUB/env/lib/python3.9/site-packages/pdfplumber/display.py", line 39, in get_page_image
    with wand.image.Image(resolution=resolution, **spec) as img_init:
  File "/home/leshem/ACLPUB/env/lib/python3.9/site-packages/wand/image.py", line 9110, in __init__
    self.read(filename=filename)
  File "/home/leshem/ACLPUB/env/lib/python3.9/site-packages/wand/image.py", line 9705, in read
    self.raise_exception()
  File "/home/leshem/ACLPUB/env/lib/python3.9/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.PolicyError: not authorized `/home/leshem/Downloads/NAACL_HLT_2021_BERT_project.pdf' @ error/constitute.c/ReadImage/412

**Comment by tuyunbin** [comment]
I used this command and it works. 
sed -i 's/<policy domain="coder" rights="none" pattern="PDF" \/>/<policy domain="coder" rights="read|write" pattern="PDF" \/>/g' /etc/ImageMagick-6/policy.xml

**Comment by borgr** [comment]
No

**Comment by tuyunbin** [comment]
Hi, I solved it and gave the solution in the last comment.

**Comment by chen-judge** [comment]
@tuyunbin 
Hi,
Can you give me a whole command?
I still fail to make it work.
Thanks!

**Comment by tuyunbin** [comment]
@chen-judge Hi, I just input this line in the linux terminal:

sed -i 's/<policy domain="coder" rights="none" pattern="PDF" \/>/<policy domain="coder" rights="read|write" pattern="PDF" \/>/g' /etc/ImageMagick-6/policy.xml
![image](https://user-images.githubusercontent.com/22414019/119360302-0e618b00-bcdd-11eb-81db-1fcc86fc5f02.png)

**Comment by chen-judge** [comment]
@tuyunbin 
I follow your command, but why does this happen?

![image](https://user-images.githubusercontent.com/31342901/119362136-fb4fba80-bcde-11eb-82e2-8ab97a56dc3b.png)

**Comment by tuyunbin** [comment]
@chen-judge I think since the github hiddes some characters like " \ " behind the "PDF", you missed this character and you can check whether other character is missed based on the following figure:
![image](https://user-images.githubusercontent.com/22414019/119420664-9b353480-bd2f-11eb-9ff3-594d91c3b4f5.png)

**Comment by chen-judge** [comment]
@tuyunbin  Thank you for your patient reply! I add the "\" and run this command successfully. But when running formatchecker.py, I still meet "wand.exceptions.PolicyError".

**Comment by tuyunbin** [comment]
@chen-judge I found this solution in Google and it worked for me, so, you can find other solutions in Google. But if you cannot find proper method, you can send your paper to me and I will help check this paper.

**Comment by zilunpeng** [comment]
I followed the solution here (https://stackoverflow.com/questions/52699608/wand-policy-error-error-constitute-c-readimage-412) and it solved my problem
