### ISSUE TITLE
attempt to perform an operation not allowed by the security policy `PDF'

### ISSUE THREAD

**Issue by hadifar** [yz-joey/ACLPUB#4]
When I run the following script it throws a security exception which is not clear for me. Would you please help me with this?

```
sudo python3 aclpub_check/formatchecker.py --paper_type short 1764_Paper_1.pdf 
Checking 1764_Paper_1.pdf

```

here is the error:

```
Traceback (most recent call last):
  File "aclpub_check/formatchecker.py", line 352, in <module>
    main()
  File "aclpub_check/formatchecker.py", line 349, in main
    worker(submission)
  File "aclpub_check/formatchecker.py", line 314, in worker
    Formatter().format_check(submission=pdf_path, paper_type=args.paper_type)
  File "aclpub_check/formatchecker.py", line 65, in format_check
    self.check_page_margin()
  File "aclpub_check/formatchecker.py", line 173, in check_page_margin
    im = self.pdf.pages[page].to_image(resolution=150)
  File "/usr/local/lib/python3.7/dist-packages/pdfplumber/page.py", line 299, in to_image
    return PageImage(self, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pdfplumber/display.py", line 54, in __init__
    page.pdf.stream, page.page_number - 1, resolution
  File "/usr/local/lib/python3.7/dist-packages/pdfplumber/display.py", line 39, in get_page_image
    with wand.image.Image(resolution=resolution, **spec) as img_init:
  File "/usr/local/lib/python3.7/dist-packages/wand/image.py", line 9110, in __init__
    self.read(filename=filename)
  File "/usr/local/lib/python3.7/dist-packages/wand/image.py", line 9705, in read
    self.raise_exception()
  File "/usr/local/lib/python3.7/dist-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.PolicyError: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408

```

**Comment by ag027592** [comment]
I have faced the same issue!

**Comment by ShouryaAggarwal** [comment]
Try the fix mentioned here - https://stackoverflow.com/questions/52699608/wand-policy-error-error-constitute-c-readimage-412

I had a similar error and using the fix worked for me. Hope it helps :)
