### ISSUE TITLE
Getting Error ImageMagick

### ISSUE THREAD

**Issue by ShubhamKumarNigam** [yz-joey/ACLPUB#5]
```
Traceback (most recent call last):
  File "/anaconda3/envs/lnlp/lib/python3.7/site-packages/wand/api.py", line 151, in <module>
    libraries = load_library()
  File "/anaconda3/envs/lnlp/lib/python3.7/site-packages/wand/api.py", line 140, in load_library
    raise IOError('cannot find library; tried paths: ' + repr(tried_paths))
OSError: cannot find library; tried paths: ['/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWand.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWandHDRI.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWandHDRI-2.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWand-7.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWand-7HDRI.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWand-7HDRI-2.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWand-7.Q8.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWand-7.Q8HDRI.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWand-7.Q8HDRI-2.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWand-7.Q16.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWand-7.Q16HDRI.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWand-7.Q16HDRI-2.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWand-6.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWand-6HDRI.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWand-6HDRI-2.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWand-Q16.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWand-Q16HDRI.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWand-Q16HDRI-2.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWand-Q8.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWand-Q8HDRI.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWand-Q8HDRI-2.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWand-6.Q16.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWand-6.Q16HDRI.dylib', '/usr/local/Cellar/imagemagick@6/6.9.9-31/lib/libMagickWand-6.Q16HDRI-2.dylib']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aclpub_check/formatchecker.py", line 352, in <module>
    main()
  File "aclpub_check/formatchecker.py", line 349, in main
    worker(submission)
  File "aclpub_check/formatchecker.py", line 314, in worker
    Formatter().format_check(submission=pdf_path, paper_type=args.paper_type)
  File "aclpub_check/formatchecker.py", line 65, in format_check
    self.check_page_margin()
  File "aclpub_check/formatchecker.py", line 173, in check_page_margin
    im = self.pdf.pages[page].to_image(resolution=150)
  File "/anaconda3/envs/lnlp/lib/python3.7/site-packages/pdfplumber/page.py", line 303, in to_image
    from .display import PageImage, DEFAULT_RESOLUTION
  File "/anaconda3/envs/lnlp/lib/python3.7/site-packages/pdfplumber/display.py", line 6, in <module>
    import wand.image
  File "/anaconda3/envs/lnlp/lib/python3.7/site-packages/wand/image.py", line 18, in <module>
    from . import assertions
  File "/anaconda3/envs/lnlp/lib/python3.7/site-packages/wand/assertions.py", line 155, in <module>
    from .color import Color  # noqa: E402
  File "/anaconda3/envs/lnlp/lib/python3.7/site-packages/wand/color.py", line 10, in <module>
    from .api import library
  File "/anaconda3/envs/lnlp/lib/python3.7/site-packages/wand/api.py", line 177, in <module>
    'Try to install:\n  ' + msg)
ImportError: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  brew install freetype imagemagick
```

System Information
macOS Mojave
version 10.14.4

**Comment by haolibai** [comment]
same here.

**Comment by kevincstowe** [comment]
This was fixed for me by installing ImageMagick from here:
https://imagemagick.org/script/download.php

Which then caused another error, which required downloading and installing Ghostscript here:
https://www.ghostscript.com/download.html
